### ISSUE TITLE
Can this action be used in private repos?

### ISSUE THREAD

**Issue by stefanobartoletti** [wearerequired/git-mirror-action#13]
As the title says, I'm wondering if this action can be used in private repos.

I'm mirroring some of my repos here on GitHub to GitLab, and everything went fine with some that are public.

When I tried to do the same thing to a couple repos that are private here on GitHub, the action fails, giving me this output

```
Cloning into bare repository 'sb-website-wip.git'...
SOURCE=git@github.com:stefanobartoletti/sb-website-wip.git
DESTINATION=git@gitlab.com:stefanobartoletti/sb-website-wip.git
Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I have configured the repos in the same way of the working public ones, the only difference is that these are private.

Is there a way to solve this?

**Comment by grappler** [comment]
Yes, this action can be used for private GitHub repos. We currently have it use for a private repo ourselves.

Have you correctly setup the `SSH_PRIVATE_KEY`? THe SSH key without a passphrase must have access to both repositories.

**Comment by stefanobartoletti** [comment]
Yes, everything is configured properly, but it isn't working

**Comment by grappler** [comment]
If it is configured properly then it would work as it is working for us. I am not sure how else I can help you.

When I run I try to clone your private repo I get the same error as you mentioned and this is because my SSH-Key is not added to [your account](https://github.com/settings/keys)
```
git clone git@github.com:stefanobartoletti/sb-website-wip.git
Cloning into 'sb-website-wip'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

You can test that your SSH Key works correctly with a command like `ssh-agent bash -c 'ssh-add /somewhere/yourkey; git clone git@github.com:user/project.git'`

This SSH Key would be saved as [a secret](https://github.com/stefanobartoletti/sb-website-wip/settings/secrets/actions).

**Comment by stefanobartoletti** [comment]
Thank you, I had to add my Key to my profile. It was not clear that I had to do this.

**Comment by ocean90** [comment]
Glad it's working now! I have updated the documentation in https://github.com/wearerequired/git-mirror-action/commit/a3d698669230bf295361234b13e6cdcbc0036e21 to make this a bit clearer.
